export const GET_COURSE_START = 'CONVERTER_PAGE/GET_COURSE_START';
export const GET_COURSE_SUCCESS = 'CONVERTER_PAGE/GET_COURSE_SUCCESS';
export const GET_COURSE_FAILED = 'CONVERTER_PAGE/GET_COURSE_FAILED';