export const LOGOUT = 'GLOBAL/LOGOUT';
export const LOGIN_START = 'GLOBAL/LOGIN_START';
export const LOGIN_FAILED = 'GLOBAL/LOGIN_FAILED';
export const LOGIN_SUCCESS = 'GLOBAL/LOGIN_SUCCESS';
export const REDIRECT = 'GLOBAL/REDIRECT';
export const CLEAR_LOGIN_ERROR = 'GLOBAL/CLEAR_LOGIN_ERROR';