export const GET_USER_INFO_START = 'PROFILE/GET_USER_INFO_START';
export const GET_USER_INFO_SUCCESS = 'PROFILE/GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'PROFILE/GET_USER_INFO_FAILED';