export const UPDATE_USER_NAME = 'LOGIN_PAGE/UPDATE_USER_NAME';
export const UPDATE_USER_PASSWORD = 'LOGIN_PAGE/UPDATE_USER_PASSWORD';
export const LOGIN_ERROR = `LOGIN_PAGE/LOGIN_ERROR`;
export const CLEAR_USER_DATA = `LOGIN_PAGE/CLEAR_USER_DATA`;
export const REDIRECT = `LOGIN_PAGE/REDIRECT`;